# Generated by Django 3.0.3 on 2020-02-22 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='product',
            table='store_product',
        ),
    ]
